# .github/actions/common-steps/action.yml
name: "Common Steps"
description: "Common steps for checking out code, installing uv, setting up Python, and installing the project."
inputs:
  python-version:
    description: "The Python version to set up."
    required: true
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install the project
      shell: bash
      run: uv sync
