# .github/workflows/publish.yml

name: Publish Python Package

on:
  push:
    branches:
      - main # Replace with your default branch

jobs:
  build-and-publish:
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Build the project
        run: uv build

      - name: Publish to pypi
        run: uv publish --token  ${{ secrets.PYPI_API_TOKEN }}
