# .github/workflows/ci-and-publish.yml
name: CI and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run common steps
        uses: ./.github/actions/common-steps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest

  publish:
    name: Publish on PyPI on Python ${{ matrix.python-version }}
    if: github.event_name == 'push'
    needs: test
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Run common steps
        uses: ./.github/actions/common-steps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the project
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
